import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";

import { useMoralis } from "react-moralis";

const Home: NextPage = () => {
  const { isAuthenticated, authenticate } = useMoralis();
  useEffect(() => {
    console.log(isAuthenticated, "isAuthenticated");
  }, [isAuthenticated]);

  return (
    <>
      <Head>
        <title>Solana Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {isAuthenticated && <p>Welcome to Solana Ecosystem</p>}
        {!isAuthenticated && (
          <button
            onClick={() =>
              authenticate({
                type: "sol",
                signingMessage: "Welcome to Solana Ecosystem",
              })
            }
          >
            Auth
          </button>
        )}
      </div>
    </>
  );
};

export default Home;
